
name: Main

on:
  push:

jobs:
  anything:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Create output
        run:
          echo Hello > hello.txt

      - name: See if it still exists in next step
        run:
          ls -al
