
name: Main

on:
  push:

env:
  SLACK_MESSAGE_FILENAME: slack_message.txt

jobs:
  anything:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Get the Slack message
        id: slack_message
        run: |
          echo "" > "${SLACK_MESSAGE_FILENAME}"
          echo "Hello" >> "${SLACK_MESSAGE_FILENAME}"
          echo "World" >> "${SLACK_MESSAGE_FILENAME}"
          
          cat "${SLACK_MESSAGE_FILENAME}"
          #echo "content=$(cat "${SLACK_MESSAGE_FILENAME}")" >> ${GITHUB_OUTPUT}          
          {
            echo "SLACK_MESSAGE<<EOF"
            cat "${SLACK_MESSAGE_FILENAME}"
            echo "EOF"
          } >> ${GITHUB_ENV}          

      - name: Send secrets needing attention message to Slack
        if: ${{ env.SLACK_MESSAGE != '' }}
        run: |
          echo "some secrets need attention"
          echo ":${{ env.SLACK_MESSAGE }}:"

      - name: Send no-secrets need attention message to Slack
        if: ${{ env.SLACK_MESSAGE == '' }}
        run: |
          echo "no secrets need attention"
          echo ":${{ env.SLACK_MESSAGE }}:"

      - name: third
        if: failure()
        run:
          echo "Send failure message to Slack"
