
name: Main

on:
  push:

env:
  NEW_BASE_IMAGE: cyberdojo/sinatra-base:759c4e9@sha256:d5f87f343a9f88a598b810c0f02b81db0bb67319701a956aec3577cbd51c1c24

jobs:
  push-to-other-repo:
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cyber-dojo/ci-testing
          fetch-depth: 0

      - name: Create branch
        run:
          git checkout -b update-base-image

      - name: Edit Dockerfile
        run: |
          cp Dockerfile Dockerfile.original
          echo "FROM ${NEW_BASE_IMAGE}" > Dockerfile
          cat Dockerfile.original | tail -n+2 >> Dockerfile

      - name: Commit
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "Dockerfile - Automated base-image update"

      - name: Push branch
        run:
          git push
