
name: Main

on:
  push:

jobs:
  anything:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - name: Install ripgrep
        run: |
          sudo apt update
          sudo apt install ripgrep --yes
